name: Build

on:
  schedule:
    # Run every day at 6:00
    - cron: "0 6 * * *"
  push:
    branches:
      - master
      - branch-*
      - dogfood-on-*
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  build:
    runs-on: sonar-xs-public
    name: Build
    permissions:
      id-token: write  # Required for Vault OIDC authentication
      contents: write  # Required for repository access and tagging
    steps:
      - &checkout
        name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup development environment with mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12
      - name: Build and analyze with Maven
        id: build-maven
        uses: SonarSource/ci-github-actions/build-maven@c4694c3bcbf4f6f279b8184623a611b8f39c82e5
        with:
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          deploy-pull-request: true

  promote:
    needs: [ build ]
    runs-on: sonar-xs-public
    name: Promote
    permissions:
      id-token: write
      contents: write
    steps:
      - *checkout
      - name: Promote artifacts
        uses: SonarSource/ci-github-actions/promote@v1
        with:
          promote-pull-request: true
